### ISSUE TITLE
단위 테스트를 미러링 구조로 변환

### ISSUE THREAD

**Issue by koorukuroo** [CoreDotToday/CoreDotFinance#100]
현재 [test](https://github.com/CoreDotToday/CoreDotFinance/tree/master/test)가 비즈니스 로직에 따른 테스트로 구성되어 있는데, 명확한 계층 구조를 갖는 방식이 선호되고 있는 것 같습니다.
향후 늘어나는 코드의 양에 대응하기 위해 `$ROOT/$PACKAGE/$SUBPACKAGE/tests`와 같은 구성에 소스트리의 나머지 구조를 미러링 하는 형태로 단위 테스트를 하는 것이 어떤가 제안드려 봅니다~!

예시) pandas-datareader
https://github.com/pydata/pandas-datareader/tree/main/pandas_datareader
https://github.com/pydata/pandas-datareader/tree/main/pandas_datareader/tests

**Comment by DavidKimDY** [comment]
# Todo
- [x] coredotfinance/__init__.py
- [ ] coredotfinance/data.py                              
## binance
- [x] coredotfinance/binance/__init__.py
- [ ] coredotfinance/binance/api.py         
- [ ] coredotfinance/binance/binance.py
- [x] coredotfinance/binance/dataframe_util.py
- [ ] coredotfinance/binance/datetime_util.py   
- [ ] coredotfinance/binance/utils.py 
## database
- [x] coredotfinance/database/__init__.py      
- [ ] coredotfinance/database/krx_db.py
## krx        
- [x] coredotfinance/krx/__init__.py  
### api              
- [x] corexdotfinance/krx/api/__init__.py        
- [ ] coredotfinance/krx/api/data_reader.py   
- [ ] coredotfinance/krx/api/tool.py                
### core 
- [x] coredotfinance/krx/core/__init__.py      
- [ ] coredotfinance/krx/core/classify.py       
- [ ] coredotfinance/krx/core/column.py       
- [ ] coredotfinance/krx/core/fetch.py           
- [x] coredotfinance/krx/core/function_code_list.py
- [ ] coredotfinance/krx/core/jsp_util.py                  
- [x] coredotfinance/krx/core/krx_website/__init__.py
- [ ] coredotfinance/krx/core/krx_website/index.py     
- [ ] coredotfinance/krx/core/krx_website/info.py        
- [ ] coredotfinance/krx/core/krx_website/products.py
- [ ] coredotfinance/krx/core/krx_website/stock.py      
- [ ] coredotfinance/krx/core/option.py                    
- [ ] coredotfinance/krx/core/process.py                 
- [ ] coredotfinance/krx/core/webio.py
